#!/bin/bash

# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

# Don't forget to "chmod +x .openshift/action_hooks/build"

# Use repository htaccess if exists
#if [ -f ${OPENSHIFT_REPO_DIR}.openshift/config/.htaccess ]; then
#  cp -f ${OPENSHIFT_REPO_DIR}.openshift/config/.htaccess ${OPENSHIFT_REPO_DIR}web/.htaccess
#fi
