<?php
return [
    [
        'user_id' => 1,
        'firstname' => 'Joe',
        'lastname' => 'Smith',
        'bio' => 'This is my biooo',
        'receive_emails' => 1,
        'share_details' => 1,
        'phone' => '555-123-9900',
        'skype' => NULL,
        'address1' => '123 Nowhere Drive',
        'address2' => 'Apt X',
        'city' => 'Beverly Hills',
        'state' => 'CA',
        'zip' => '90210',
        'country' => 'USA',
        'created_at' => '1391885313',
        'updated_at' => '1391885313',
    ],
    [
        'user_id' => 2,
        'firstname' => 'James',
        'lastname' => 'Bond',
        'bio' => 'Bond, James Bond',
        'receive_emails' => 1,
        'share_details' => 1,
        'phone' => '007-007-0007',
        'skype' => NULL,
        'address1' => '007 Bond Street',
        'address2' => 'Suite #007',
        'city' => 'New York',
        'state' => 'NY',
        'zip' => '10007',
        'country' => 'USA',
        'created_at' => 1391885313,
        'updated_at' => 1391885313,
    ],
];
